version: '3'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    build: ./chefbot
    container_name: ros_master
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  talker:
    build: ./chefbot
    container_name: ros_client1
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=talker"
    command: stdbuf -o L rostopic pub /chatter std_msgs/String "hello" -r 1
    networks:
      - ros
    restart: always

  listener:
    build: ./chefbot
    container_name: ros_client2
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=listener"
    command: stdbuf -o L rostopic echo /chatter
    networks:
      - ros
    restart: always